[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "collaborative perception"
authors = [{name = "proanmer", email = "bukalala174@gmail.com"}]
dynamic = ["version", "description"]
